// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Food struct {
	ID     string `json:"id"`
	Color  string `json:"color"`
	Serves int    `json:"serves"`
}

type NewFood struct {
	ID     string `json:"id"`
	Color  string `json:"color"`
	Serves int    `json:"serves"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
